name: offset_stack
description: offset_stack is a pure dart package that allows you to create an widget stack with offset.
homepage: https://github.com/conghaonet/offset_stack
repository: https://github.com/conghaonet/offset_stack
version: 0.0.1

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.18.6 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
